apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-dedup-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-dedup
  template:
    metadata:
      labels:
        app: email-dedup
    spec:
      containers:
      - name: email-dedup
        image: email-dedup-local:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENV
          value: "production"
        - name: KAFKA_SERVERS
          value: "host.docker.internal:9092"
        - name: DB_HOST
          value: "host.docker.internal"

---
apiVersion: v1
kind: Service
metadata:
  name: email-dedup-service
spec:
  type: NodePort
  selector:
    app: email-dedup
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080