apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-dedup-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-dedup
  template:
    metadata:
      labels:
        app: email-dedup
    spec:
      # Wait for Kafka to be reachable before starting the app
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done"]

      containers:
        - name: email-dedup
          image: email-dedup-local:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "production"
            
            - name: KAFKA_SERVERS
              value: "kafka:9092"
            - name: KAFKA_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: KAFKA_SASL_MECHANISM
              value: "SCRAM-SHA-256"
            - name: KAFKA_SASL_USERNAME
              value: "user1"
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-user-passwords
                  key: client-passwords
            
            - name: DB_HOST
              value: "host.docker.internal"

---
apiVersion: v1
kind: Service
metadata:
  name: email-dedup-service
spec:
  type: NodePort
  selector:
    app: email-dedup
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080