[kafka]
bootstrap_servers = "localhost:9092"
topic = "email-ingest"
    [kafka.producer]
    client_id = "email-ingest-pub"

    [kafka.consumer]
    client_id = "email-ingest-sub"
    group_id = "email-ingest-sub-group"


[email]
read_dir = "data/eval"

[database]
username = "root"
password = "tianyu1996"
host = "localhost"
port = 3306
database_name = "email_dedup"